// Code generated by protoc-gen-go. DO NOT EDIT.
// source: directory_list.proto

package rpc

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DirectoryListRequest_Sort int32

const (
	DirectoryListRequest_DescType DirectoryListRequest_Sort = 0
	DirectoryListRequest_AscType  DirectoryListRequest_Sort = 1
	DirectoryListRequest_DescName DirectoryListRequest_Sort = 2
	DirectoryListRequest_AscName  DirectoryListRequest_Sort = 3
	DirectoryListRequest_DescTime DirectoryListRequest_Sort = 4
	DirectoryListRequest_AscDesc  DirectoryListRequest_Sort = 5
)

var DirectoryListRequest_Sort_name = map[int32]string{
	0: "DescType",
	1: "AscType",
	2: "DescName",
	3: "AscName",
	4: "DescTime",
	5: "AscDesc",
}

var DirectoryListRequest_Sort_value = map[string]int32{
	"DescType": 0,
	"AscType":  1,
	"DescName": 2,
	"AscName":  3,
	"DescTime": 4,
	"AscDesc":  5,
}

func (x DirectoryListRequest_Sort) String() string {
	return proto.EnumName(DirectoryListRequest_Sort_name, int32(x))
}

func (DirectoryListRequest_Sort) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fce45d37c1e4326f, []int{0, 0}
}

// DirectoryListRequest represent the list directory request
type DirectoryListRequest struct {
	Token                string                    `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Secret               *wrappers.StringValue     `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	SubDir               *wrappers.StringValue     `protobuf:"bytes,3,opt,name=sub_dir,json=subDir,proto3" json:"sub_dir,omitempty"`
	Sort                 DirectoryListRequest_Sort `protobuf:"varint,4,opt,name=sort,proto3,enum=bigfile.directory_list.DirectoryListRequest_Sort" json:"sort,omitempty"`
	Limit                *wrappers.UInt32Value     `protobuf:"bytes,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               *wrappers.UInt32Value     `protobuf:"bytes,6,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *DirectoryListRequest) Reset()         { *m = DirectoryListRequest{} }
func (m *DirectoryListRequest) String() string { return proto.CompactTextString(m) }
func (*DirectoryListRequest) ProtoMessage()    {}
func (*DirectoryListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fce45d37c1e4326f, []int{0}
}

func (m *DirectoryListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirectoryListRequest.Unmarshal(m, b)
}
func (m *DirectoryListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirectoryListRequest.Marshal(b, m, deterministic)
}
func (m *DirectoryListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirectoryListRequest.Merge(m, src)
}
func (m *DirectoryListRequest) XXX_Size() int {
	return xxx_messageInfo_DirectoryListRequest.Size(m)
}
func (m *DirectoryListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DirectoryListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DirectoryListRequest proto.InternalMessageInfo

func (m *DirectoryListRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *DirectoryListRequest) GetSecret() *wrappers.StringValue {
	if m != nil {
		return m.Secret
	}
	return nil
}

func (m *DirectoryListRequest) GetSubDir() *wrappers.StringValue {
	if m != nil {
		return m.SubDir
	}
	return nil
}

func (m *DirectoryListRequest) GetSort() DirectoryListRequest_Sort {
	if m != nil {
		return m.Sort
	}
	return DirectoryListRequest_DescType
}

func (m *DirectoryListRequest) GetLimit() *wrappers.UInt32Value {
	if m != nil {
		return m.Limit
	}
	return nil
}

func (m *DirectoryListRequest) GetOffset() *wrappers.UInt32Value {
	if m != nil {
		return m.Offset
	}
	return nil
}

// DirectoryListResponse represent the token delete response
type DirectoryListResponse struct {
	RequestId            uint64   `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Total                int32    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Pages                int32    `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	Files                []*File  `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DirectoryListResponse) Reset()         { *m = DirectoryListResponse{} }
func (m *DirectoryListResponse) String() string { return proto.CompactTextString(m) }
func (*DirectoryListResponse) ProtoMessage()    {}
func (*DirectoryListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fce45d37c1e4326f, []int{1}
}

func (m *DirectoryListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirectoryListResponse.Unmarshal(m, b)
}
func (m *DirectoryListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirectoryListResponse.Marshal(b, m, deterministic)
}
func (m *DirectoryListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirectoryListResponse.Merge(m, src)
}
func (m *DirectoryListResponse) XXX_Size() int {
	return xxx_messageInfo_DirectoryListResponse.Size(m)
}
func (m *DirectoryListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DirectoryListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DirectoryListResponse proto.InternalMessageInfo

func (m *DirectoryListResponse) GetRequestId() uint64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *DirectoryListResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *DirectoryListResponse) GetPages() int32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *DirectoryListResponse) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

func init() {
	proto.RegisterEnum("bigfile.directory_list.DirectoryListRequest_Sort", DirectoryListRequest_Sort_name, DirectoryListRequest_Sort_value)
	proto.RegisterType((*DirectoryListRequest)(nil), "bigfile.directory_list.DirectoryListRequest")
	proto.RegisterType((*DirectoryListResponse)(nil), "bigfile.directory_list.DirectoryListResponse")
}

func init() { proto.RegisterFile("directory_list.proto", fileDescriptor_fce45d37c1e4326f) }

var fileDescriptor_fce45d37c1e4326f = []byte{
	// 460 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x51, 0xdd, 0x8a, 0xd3, 0x40,
	0x18, 0xdd, 0x34, 0xc9, 0xae, 0xfb, 0xd5, 0x95, 0x32, 0x54, 0x09, 0x45, 0xd7, 0xd2, 0xab, 0x5c,
	0x68, 0x8a, 0x59, 0x7d, 0x00, 0x4b, 0x15, 0x16, 0x45, 0xca, 0xac, 0xba, 0xe0, 0x4d, 0xc9, 0xcf,
	0xd7, 0x38, 0x38, 0xc9, 0xc4, 0x99, 0x09, 0x65, 0xaf, 0x7c, 0x01, 0x9f, 0x42, 0xef, 0x7c, 0x42,
	0x2f, 0x25, 0x33, 0x49, 0xa1, 0xb2, 0x42, 0xbd, 0x49, 0x38, 0xe7, 0x3b, 0x67, 0xbe, 0x39, 0x73,
	0x60, 0x9c, 0x33, 0x89, 0x99, 0x16, 0xf2, 0x66, 0xcd, 0x99, 0xd2, 0x51, 0x2d, 0x85, 0x16, 0xe4,
	0x41, 0xca, 0x8a, 0x0d, 0xe3, 0x18, 0xed, 0x4f, 0x27, 0x60, 0x48, 0xa3, 0x99, 0x9c, 0x17, 0x42,
	0x14, 0x1c, 0xe7, 0x06, 0xa5, 0xcd, 0x66, 0xbe, 0x95, 0x49, 0x5d, 0xa3, 0x54, 0x76, 0x3e, 0xfb,
	0xe9, 0xc2, 0x78, 0xd9, 0xdb, 0xdf, 0x32, 0xa5, 0x29, 0x7e, 0x6d, 0x50, 0x69, 0x32, 0x06, 0x5f,
	0x8b, 0x2f, 0x58, 0x05, 0xce, 0xd4, 0x09, 0x4f, 0xa9, 0x05, 0xe4, 0x39, 0x1c, 0x2b, 0xcc, 0x24,
	0xea, 0x60, 0x30, 0x75, 0xc2, 0x61, 0xfc, 0x30, 0xb2, 0xe7, 0x47, 0xfd, 0xf9, 0xd1, 0x95, 0x96,
	0xac, 0x2a, 0x3e, 0x26, 0xbc, 0x41, 0xda, 0x69, 0xc9, 0x0b, 0x38, 0x51, 0x4d, 0xba, 0xce, 0x99,
	0x0c, 0xdc, 0x83, 0x6c, 0x4d, 0xba, 0x64, 0x92, 0xbc, 0x02, 0x4f, 0x09, 0xa9, 0x03, 0x6f, 0xea,
	0x84, 0xf7, 0xe2, 0x67, 0xd1, 0xed, 0x71, 0xa3, 0xdb, 0xae, 0x1f, 0x5d, 0x09, 0xa9, 0xa9, 0xb1,
	0x93, 0x18, 0x7c, 0xce, 0x4a, 0xa6, 0x03, 0xff, 0x1f, 0xbb, 0x3f, 0x5c, 0x56, 0xfa, 0x22, 0xb6,
	0xbb, 0xad, 0xb4, 0xcd, 0x29, 0x36, 0x1b, 0x85, 0x3a, 0x38, 0x3e, 0xc0, 0xd4, 0x69, 0x67, 0xd7,
	0xe0, 0xb5, 0x7b, 0xc9, 0x5d, 0xb8, 0xb3, 0x44, 0x95, 0xbd, 0xbf, 0xa9, 0x71, 0x74, 0x44, 0x86,
	0x70, 0xf2, 0xb2, 0x03, 0x4e, 0x3f, 0x7a, 0x97, 0x94, 0x38, 0x1a, 0x74, 0x23, 0x03, 0xdc, 0x9d,
	0x8b, 0x95, 0x38, 0xf2, 0xba, 0x51, 0x4b, 0x8c, 0xfc, 0xd9, 0x77, 0x07, 0xee, 0xff, 0x15, 0x53,
	0xd5, 0xa2, 0x52, 0x48, 0x1e, 0x01, 0x48, 0x1b, 0x79, 0xcd, 0x72, 0xd3, 0x95, 0x47, 0x4f, 0x3b,
	0xe6, 0x32, 0xb7, 0x2d, 0xea, 0x84, 0x9b, 0xba, 0x7c, 0x6a, 0x41, 0xcb, 0xd6, 0x49, 0x81, 0xca,
	0xb4, 0xe1, 0x53, 0x0b, 0x48, 0x08, 0x7e, 0xfb, 0xbc, 0x2a, 0xf0, 0xa6, 0x6e, 0x38, 0x8c, 0xc9,
	0xee, 0xbd, 0xcd, 0xe7, 0x35, 0xe3, 0x48, 0xad, 0x20, 0xfe, 0x06, 0x67, 0x7b, 0xb7, 0x21, 0x15,
	0x9c, 0xe5, 0x7b, 0xc4, 0x93, 0xff, 0x29, 0x6b, 0xf2, 0xf4, 0x40, 0xb5, 0xcd, 0x3c, 0x3b, 0x5a,
	0x6c, 0x61, 0x9c, 0x89, 0x72, 0xe7, 0xea, 0x4b, 0x59, 0x90, 0x3d, 0xc3, 0xaa, 0xa5, 0x57, 0xce,
	0xa7, 0xf3, 0x82, 0xe9, 0xcf, 0x4d, 0x1a, 0x65, 0xa2, 0x9c, 0x77, 0x96, 0xdd, 0x5f, 0xd6, 0xd9,
	0x6f, 0xc7, 0xf9, 0x31, 0x70, 0x17, 0x2b, 0xfa, 0x6b, 0xf0, 0x78, 0xd1, 0x9d, 0xb8, 0xea, 0x6b,
	0xbe, 0x46, 0xce, 0xdf, 0x54, 0x62, 0x5b, 0xb5, 0xfd, 0xa9, 0xf4, 0xd8, 0xac, 0xba, 0xf8, 0x13,
	0x00, 0x00, 0xff, 0xff, 0x23, 0x2a, 0x15, 0x8f, 0x91, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DirectoryListClient is the client API for DirectoryList service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DirectoryListClient interface {
	DirectoryList(ctx context.Context, in *DirectoryListRequest, opts ...grpc.CallOption) (*DirectoryListResponse, error)
}

type directoryListClient struct {
	cc *grpc.ClientConn
}

func NewDirectoryListClient(cc *grpc.ClientConn) DirectoryListClient {
	return &directoryListClient{cc}
}

func (c *directoryListClient) DirectoryList(ctx context.Context, in *DirectoryListRequest, opts ...grpc.CallOption) (*DirectoryListResponse, error) {
	out := new(DirectoryListResponse)
	err := c.cc.Invoke(ctx, "/bigfile.directory_list.DirectoryList/directoryList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DirectoryListServer is the server API for DirectoryList service.
type DirectoryListServer interface {
	DirectoryList(context.Context, *DirectoryListRequest) (*DirectoryListResponse, error)
}

// UnimplementedDirectoryListServer can be embedded to have forward compatible implementations.
type UnimplementedDirectoryListServer struct {
}

func (*UnimplementedDirectoryListServer) DirectoryList(ctx context.Context, req *DirectoryListRequest) (*DirectoryListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DirectoryList not implemented")
}

func RegisterDirectoryListServer(s *grpc.Server, srv DirectoryListServer) {
	s.RegisterService(&_DirectoryList_serviceDesc, srv)
}

func _DirectoryList_DirectoryList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DirectoryListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectoryListServer).DirectoryList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bigfile.directory_list.DirectoryList/DirectoryList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectoryListServer).DirectoryList(ctx, req.(*DirectoryListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DirectoryList_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bigfile.directory_list.DirectoryList",
	HandlerType: (*DirectoryListServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "directoryList",
			Handler:    _DirectoryList_DirectoryList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "directory_list.proto",
}
