// Code generated by protoc-gen-go. DO NOT EDIT.
// source: file_delete.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// FileDeleteRequest represent the token delete request
type FileDeleteRequest struct {
	Token                string                `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	FileUid              string                `protobuf:"bytes,2,opt,name=file_uid,json=fileUid,proto3" json:"file_uid,omitempty"`
	ForceDeleteDir       bool                  `protobuf:"varint,3,opt,name=force_delete_dir,json=forceDeleteDir,proto3" json:"force_delete_dir,omitempty"`
	Secret               *wrappers.StringValue `protobuf:"bytes,4,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *FileDeleteRequest) Reset()         { *m = FileDeleteRequest{} }
func (m *FileDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*FileDeleteRequest) ProtoMessage()    {}
func (*FileDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_37676b62f991a3b0, []int{0}
}

func (m *FileDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileDeleteRequest.Unmarshal(m, b)
}
func (m *FileDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileDeleteRequest.Marshal(b, m, deterministic)
}
func (m *FileDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileDeleteRequest.Merge(m, src)
}
func (m *FileDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_FileDeleteRequest.Size(m)
}
func (m *FileDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FileDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FileDeleteRequest proto.InternalMessageInfo

func (m *FileDeleteRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *FileDeleteRequest) GetFileUid() string {
	if m != nil {
		return m.FileUid
	}
	return ""
}

func (m *FileDeleteRequest) GetForceDeleteDir() bool {
	if m != nil {
		return m.ForceDeleteDir
	}
	return false
}

func (m *FileDeleteRequest) GetSecret() *wrappers.StringValue {
	if m != nil {
		return m.Secret
	}
	return nil
}

// FileDeleteResponse represent the token delete response
type FileDeleteResponse struct {
	RequestId            uint64   `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	File                 *File    `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileDeleteResponse) Reset()         { *m = FileDeleteResponse{} }
func (m *FileDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*FileDeleteResponse) ProtoMessage()    {}
func (*FileDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_37676b62f991a3b0, []int{1}
}

func (m *FileDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileDeleteResponse.Unmarshal(m, b)
}
func (m *FileDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileDeleteResponse.Marshal(b, m, deterministic)
}
func (m *FileDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileDeleteResponse.Merge(m, src)
}
func (m *FileDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_FileDeleteResponse.Size(m)
}
func (m *FileDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FileDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FileDeleteResponse proto.InternalMessageInfo

func (m *FileDeleteResponse) GetRequestId() uint64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *FileDeleteResponse) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

func init() {
	proto.RegisterType((*FileDeleteRequest)(nil), "bigfile.file_delete.FileDeleteRequest")
	proto.RegisterType((*FileDeleteResponse)(nil), "bigfile.file_delete.FileDeleteResponse")
}

func init() { proto.RegisterFile("file_delete.proto", fileDescriptor_37676b62f991a3b0) }

var fileDescriptor_37676b62f991a3b0 = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xdd, 0xb6, 0xd6, 0x76, 0x0a, 0x6a, 0xd7, 0x1e, 0x62, 0xd1, 0x5a, 0x7a, 0xa8, 0x39,
	0x6d, 0xa1, 0xfa, 0x09, 0x42, 0x11, 0xc4, 0x4b, 0x88, 0xff, 0x40, 0x0f, 0xa1, 0x49, 0xa6, 0x71,
	0x31, 0xcd, 0xc6, 0xcd, 0x86, 0xe2, 0xd7, 0x11, 0x4f, 0x7e, 0x42, 0x8f, 0x92, 0x4d, 0xd2, 0x16,
	0x14, 0x3c, 0x85, 0x79, 0xf3, 0xf2, 0xe6, 0xb7, 0x0f, 0xba, 0x0b, 0x1e, 0xa1, 0x1b, 0x60, 0x84,
	0x0a, 0x59, 0x22, 0x85, 0x12, 0xf4, 0xc8, 0xe3, 0x61, 0xae, 0xb2, 0xad, 0x55, 0x1f, 0xb4, 0xa2,
	0x0d, 0xfd, 0x41, 0x28, 0x44, 0x18, 0xe1, 0x44, 0x4f, 0x5e, 0xb6, 0x98, 0xac, 0xe4, 0x3c, 0x49,
	0x50, 0xa6, 0xc5, 0x7e, 0xf4, 0x49, 0xa0, 0x7b, 0xc5, 0x23, 0x9c, 0xe9, 0x5f, 0x1d, 0x7c, 0xcb,
	0x30, 0x55, 0xb4, 0x07, 0xbb, 0x4a, 0xbc, 0x62, 0x6c, 0x90, 0x21, 0x31, 0xdb, 0x4e, 0x31, 0xd0,
	0x63, 0x68, 0xe9, 0x33, 0x19, 0x0f, 0x8c, 0x9a, 0x5e, 0xec, 0xe5, 0xf3, 0x3d, 0x0f, 0xa8, 0x09,
	0x87, 0x0b, 0x21, 0xfd, 0x0a, 0xc1, 0x0d, 0xb8, 0x34, 0xea, 0x43, 0x62, 0xb6, 0x9c, 0x7d, 0xad,
	0x17, 0xf1, 0x33, 0x2e, 0xe9, 0x25, 0x34, 0x53, 0xf4, 0x25, 0x2a, 0xa3, 0x31, 0x24, 0x66, 0x67,
	0x7a, 0xc2, 0x0a, 0x42, 0x56, 0x11, 0xb2, 0x5b, 0x25, 0x79, 0x1c, 0x3e, 0xcc, 0xa3, 0x0c, 0x9d,
	0xd2, 0x3b, 0x7a, 0x06, 0xba, 0x4d, 0x99, 0x26, 0x22, 0x4e, 0x91, 0x9e, 0x02, 0xc8, 0x82, 0xd8,
	0xe5, 0x81, 0x66, 0x6d, 0x38, 0xed, 0x52, 0xb9, 0x0e, 0xe8, 0x18, 0x1a, 0x39, 0x9f, 0x66, 0xed,
	0x4c, 0x29, 0xdb, 0xee, 0x8a, 0xe5, 0x71, 0x8e, 0xde, 0x4f, 0x97, 0x00, 0x9b, 0x70, 0xea, 0x82,
	0xee, 0xaf, 0x9c, 0xc6, 0xec, 0x8f, 0x86, 0xd9, 0xaf, 0xc6, 0xfa, 0xe7, 0xff, 0xfa, 0x0a, 0xe6,
	0xd1, 0x8e, 0xa5, 0xa0, 0xe7, 0x8b, 0xe5, 0xda, 0x5f, 0xbd, 0xdb, 0x3a, 0xd8, 0xb8, 0xed, 0x5c,
	0xb3, 0xc9, 0xd3, 0x20, 0xe4, 0xea, 0x25, 0xf3, 0x98, 0x2f, 0x96, 0x93, 0xd2, 0xbf, 0xfe, 0xca,
	0xc4, 0xff, 0x26, 0xe4, 0xa3, 0x56, 0xb7, 0x6c, 0xe7, 0xab, 0x76, 0x66, 0x95, 0x71, 0x76, 0x55,
	0xe3, 0x23, 0x46, 0xd1, 0x4d, 0x2c, 0x56, 0xf1, 0xdd, 0x7b, 0x82, 0xa9, 0xd7, 0xd4, 0x77, 0x2e,
	0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0x8f, 0xed, 0xa0, 0xb4, 0x45, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FileDeleteClient is the client API for FileDelete service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FileDeleteClient interface {
	FileDelete(ctx context.Context, in *FileDeleteRequest, opts ...grpc.CallOption) (*FileDeleteResponse, error)
}

type fileDeleteClient struct {
	cc *grpc.ClientConn
}

func NewFileDeleteClient(cc *grpc.ClientConn) FileDeleteClient {
	return &fileDeleteClient{cc}
}

func (c *fileDeleteClient) FileDelete(ctx context.Context, in *FileDeleteRequest, opts ...grpc.CallOption) (*FileDeleteResponse, error) {
	out := new(FileDeleteResponse)
	err := c.cc.Invoke(ctx, "/bigfile.file_delete.FileDelete/fileDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileDeleteServer is the server API for FileDelete service.
type FileDeleteServer interface {
	FileDelete(context.Context, *FileDeleteRequest) (*FileDeleteResponse, error)
}

// UnimplementedFileDeleteServer can be embedded to have forward compatible implementations.
type UnimplementedFileDeleteServer struct {
}

func (*UnimplementedFileDeleteServer) FileDelete(ctx context.Context, req *FileDeleteRequest) (*FileDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileDelete not implemented")
}

func RegisterFileDeleteServer(s *grpc.Server, srv FileDeleteServer) {
	s.RegisterService(&_FileDelete_serviceDesc, srv)
}

func _FileDelete_FileDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileDeleteServer).FileDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bigfile.file_delete.FileDelete/FileDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileDeleteServer).FileDelete(ctx, req.(*FileDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FileDelete_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bigfile.file_delete.FileDelete",
	HandlerType: (*FileDeleteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "fileDelete",
			Handler:    _FileDelete_FileDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "file_delete.proto",
}
