// Code generated by protoc-gen-go. DO NOT EDIT.
// source: file_update.proto

package rpc

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// FileUpdateRequest represent the file update request
type FileUpdateRequest struct {
	Token                string                `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	FileUid              string                `protobuf:"bytes,2,opt,name=file_uid,json=fileUid,proto3" json:"file_uid,omitempty"`
	Path                 string                `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Secret               *wrappers.StringValue `protobuf:"bytes,4,opt,name=secret,proto3" json:"secret,omitempty"`
	Hidden               *wrappers.BoolValue   `protobuf:"bytes,5,opt,name=hidden,proto3" json:"hidden,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *FileUpdateRequest) Reset()         { *m = FileUpdateRequest{} }
func (m *FileUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*FileUpdateRequest) ProtoMessage()    {}
func (*FileUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bb90a24ce583932, []int{0}
}

func (m *FileUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileUpdateRequest.Unmarshal(m, b)
}
func (m *FileUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileUpdateRequest.Marshal(b, m, deterministic)
}
func (m *FileUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileUpdateRequest.Merge(m, src)
}
func (m *FileUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_FileUpdateRequest.Size(m)
}
func (m *FileUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FileUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FileUpdateRequest proto.InternalMessageInfo

func (m *FileUpdateRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *FileUpdateRequest) GetFileUid() string {
	if m != nil {
		return m.FileUid
	}
	return ""
}

func (m *FileUpdateRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *FileUpdateRequest) GetSecret() *wrappers.StringValue {
	if m != nil {
		return m.Secret
	}
	return nil
}

func (m *FileUpdateRequest) GetHidden() *wrappers.BoolValue {
	if m != nil {
		return m.Hidden
	}
	return nil
}

// FileUpdateResponse represent the response from creating file
type FileUpdateResponse struct {
	RequestId            uint64   `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	File                 *File    `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileUpdateResponse) Reset()         { *m = FileUpdateResponse{} }
func (m *FileUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*FileUpdateResponse) ProtoMessage()    {}
func (*FileUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bb90a24ce583932, []int{1}
}

func (m *FileUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileUpdateResponse.Unmarshal(m, b)
}
func (m *FileUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileUpdateResponse.Marshal(b, m, deterministic)
}
func (m *FileUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileUpdateResponse.Merge(m, src)
}
func (m *FileUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_FileUpdateResponse.Size(m)
}
func (m *FileUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FileUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FileUpdateResponse proto.InternalMessageInfo

func (m *FileUpdateResponse) GetRequestId() uint64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *FileUpdateResponse) GetFile() *File {
	if m != nil {
		return m.File
	}
	return nil
}

func init() {
	proto.RegisterType((*FileUpdateRequest)(nil), "bigfile.file_update.FileUpdateRequest")
	proto.RegisterType((*FileUpdateResponse)(nil), "bigfile.file_update.FileUpdateResponse")
}

func init() { proto.RegisterFile("file_update.proto", fileDescriptor_7bb90a24ce583932) }

var fileDescriptor_7bb90a24ce583932 = []byte{
	// 359 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x50, 0xcd, 0x4e, 0xf2, 0x40,
	0x14, 0xfd, 0x0a, 0x85, 0x4f, 0x2e, 0x0b, 0xc3, 0xc8, 0xa2, 0x36, 0x8a, 0x84, 0x05, 0xb2, 0x1a,
	0x92, 0xea, 0x13, 0x74, 0x61, 0x62, 0xdc, 0x34, 0x55, 0x34, 0xd1, 0x05, 0xe9, 0xcf, 0xa5, 0x4c,
	0x2c, 0x9d, 0xb1, 0x9d, 0x86, 0xf8, 0x3a, 0x2e, 0x7d, 0x0c, 0x9f, 0xca, 0xa5, 0xe9, 0x4c, 0xf9,
	0x49, 0x30, 0x71, 0xd5, 0xde, 0x73, 0xcf, 0xb9, 0x73, 0xce, 0x81, 0xde, 0x82, 0xa5, 0x38, 0x2f,
	0x45, 0x1c, 0x48, 0xa4, 0x22, 0xe7, 0x92, 0x93, 0x93, 0x90, 0x25, 0x15, 0x4a, 0xf7, 0x56, 0x36,
	0x28, 0x44, 0x11, 0xec, 0x41, 0xc2, 0x79, 0x92, 0xe2, 0x54, 0x4d, 0x61, 0xb9, 0x98, 0xae, 0xf3,
	0x40, 0x08, 0xcc, 0x0b, 0xbd, 0x1f, 0x7d, 0x19, 0xd0, 0xbb, 0x61, 0x29, 0xce, 0x94, 0xd4, 0xc7,
	0xb7, 0x12, 0x0b, 0x49, 0xfa, 0xd0, 0x92, 0xfc, 0x15, 0x33, 0xcb, 0x18, 0x1a, 0x93, 0x8e, 0xaf,
	0x07, 0x72, 0x0a, 0x47, 0xfa, 0x19, 0x16, 0x5b, 0x0d, 0xb5, 0xf8, 0x5f, 0xcd, 0x33, 0x16, 0x13,
	0x02, 0xa6, 0x08, 0xe4, 0xd2, 0x6a, 0x2a, 0x58, 0xfd, 0x93, 0x6b, 0x68, 0x17, 0x18, 0xe5, 0x28,
	0x2d, 0x73, 0x68, 0x4c, 0xba, 0xce, 0x19, 0xd5, 0x5e, 0xe8, 0xc6, 0x0b, 0xbd, 0x97, 0x39, 0xcb,
	0x92, 0xc7, 0x20, 0x2d, 0xd1, 0xaf, 0xb9, 0xc4, 0x81, 0xf6, 0x92, 0xc5, 0x31, 0x66, 0x56, 0x4b,
	0xa9, 0xec, 0x03, 0x95, 0xcb, 0x79, 0x5a, 0x6b, 0x34, 0x73, 0xf4, 0x02, 0x64, 0x3f, 0x43, 0x21,
	0x78, 0x56, 0x20, 0x39, 0x07, 0xc8, 0x75, 0x9e, 0x39, 0x8b, 0x55, 0x12, 0xd3, 0xef, 0xd4, 0xc8,
	0x6d, 0x4c, 0xc6, 0x60, 0x56, 0xee, 0x55, 0x92, 0xae, 0x43, 0xe8, 0x7e, 0x93, 0xb4, 0x3a, 0xe7,
	0xab, 0xbd, 0xb3, 0x02, 0xd8, 0x1d, 0x27, 0x73, 0x50, 0xed, 0xd6, 0xd3, 0x98, 0xfe, 0xd2, 0x3f,
	0x3d, 0xe8, 0xd3, 0xbe, 0xfc, 0x93, 0xa7, 0x3d, 0x8f, 0xfe, 0xb9, 0x12, 0xfa, 0x11, 0x5f, 0x6d,
	0xf9, 0x9b, 0xd4, 0xee, 0xf1, 0x8e, 0xed, 0x55, 0x98, 0x67, 0x3c, 0x0f, 0x12, 0x26, 0x97, 0x65,
	0x48, 0x23, 0xbe, 0x9a, 0xd6, 0xfc, 0xed, 0x37, 0x17, 0xd1, 0xb7, 0x61, 0x7c, 0x34, 0x9a, 0xae,
	0xe7, 0x7f, 0x36, 0x2e, 0xdc, 0xfa, 0x9c, 0xb7, 0x29, 0xf1, 0x09, 0xd3, 0xf4, 0x2e, 0xe3, 0xeb,
	0xec, 0xe1, 0x5d, 0x60, 0x11, 0xb6, 0xd5, 0x3b, 0x57, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1d,
	0xd0, 0x74, 0x2b, 0x63, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FileUpdateClient is the client API for FileUpdate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FileUpdateClient interface {
	FileUpdate(ctx context.Context, in *FileUpdateRequest, opts ...grpc.CallOption) (*FileUpdateResponse, error)
}

type fileUpdateClient struct {
	cc *grpc.ClientConn
}

func NewFileUpdateClient(cc *grpc.ClientConn) FileUpdateClient {
	return &fileUpdateClient{cc}
}

func (c *fileUpdateClient) FileUpdate(ctx context.Context, in *FileUpdateRequest, opts ...grpc.CallOption) (*FileUpdateResponse, error) {
	out := new(FileUpdateResponse)
	err := c.cc.Invoke(ctx, "/bigfile.file_update.FileUpdate/fileUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileUpdateServer is the server API for FileUpdate service.
type FileUpdateServer interface {
	FileUpdate(context.Context, *FileUpdateRequest) (*FileUpdateResponse, error)
}

// UnimplementedFileUpdateServer can be embedded to have forward compatible implementations.
type UnimplementedFileUpdateServer struct {
}

func (*UnimplementedFileUpdateServer) FileUpdate(ctx context.Context, req *FileUpdateRequest) (*FileUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileUpdate not implemented")
}

func RegisterFileUpdateServer(s *grpc.Server, srv FileUpdateServer) {
	s.RegisterService(&_FileUpdate_serviceDesc, srv)
}

func _FileUpdate_FileUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileUpdateServer).FileUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bigfile.file_update.FileUpdate/FileUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileUpdateServer).FileUpdate(ctx, req.(*FileUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FileUpdate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bigfile.file_update.FileUpdate",
	HandlerType: (*FileUpdateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "fileUpdate",
			Handler:    _FileUpdate_FileUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "file_update.proto",
}
