// Code generated by protoc-gen-go. DO NOT EDIT.
// source: token_create.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// TokenCreateRequest is used to describe the input format
// for creating token
type TokenCreateRequest struct {
	AppUid               string                `protobuf:"bytes,1,opt,name=app_uid,json=appUid,proto3" json:"app_uid,omitempty"`
	Nonce                string                `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Sign                 string                `protobuf:"bytes,3,opt,name=sign,proto3" json:"sign,omitempty"`
	Path                 *wrappers.StringValue `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Ip                   *wrappers.StringValue `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
	Secret               *wrappers.StringValue `protobuf:"bytes,6,opt,name=secret,proto3" json:"secret,omitempty"`
	AvailableTimes       *wrappers.UInt32Value `protobuf:"bytes,7,opt,name=available_times,json=availableTimes,proto3" json:"available_times,omitempty"`
	ReadOnly             *wrappers.BoolValue   `protobuf:"bytes,8,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	ExpiredAt            *timestamp.Timestamp  `protobuf:"bytes,9,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *TokenCreateRequest) Reset()         { *m = TokenCreateRequest{} }
func (m *TokenCreateRequest) String() string { return proto.CompactTextString(m) }
func (*TokenCreateRequest) ProtoMessage()    {}
func (*TokenCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56b81cc36ca68ccc, []int{0}
}

func (m *TokenCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenCreateRequest.Unmarshal(m, b)
}
func (m *TokenCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenCreateRequest.Marshal(b, m, deterministic)
}
func (m *TokenCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenCreateRequest.Merge(m, src)
}
func (m *TokenCreateRequest) XXX_Size() int {
	return xxx_messageInfo_TokenCreateRequest.Size(m)
}
func (m *TokenCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TokenCreateRequest proto.InternalMessageInfo

func (m *TokenCreateRequest) GetAppUid() string {
	if m != nil {
		return m.AppUid
	}
	return ""
}

func (m *TokenCreateRequest) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *TokenCreateRequest) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *TokenCreateRequest) GetPath() *wrappers.StringValue {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *TokenCreateRequest) GetIp() *wrappers.StringValue {
	if m != nil {
		return m.Ip
	}
	return nil
}

func (m *TokenCreateRequest) GetSecret() *wrappers.StringValue {
	if m != nil {
		return m.Secret
	}
	return nil
}

func (m *TokenCreateRequest) GetAvailableTimes() *wrappers.UInt32Value {
	if m != nil {
		return m.AvailableTimes
	}
	return nil
}

func (m *TokenCreateRequest) GetReadOnly() *wrappers.BoolValue {
	if m != nil {
		return m.ReadOnly
	}
	return nil
}

func (m *TokenCreateRequest) GetExpiredAt() *timestamp.Timestamp {
	if m != nil {
		return m.ExpiredAt
	}
	return nil
}

// TokenCreateResponse
type TokenCreateResponse struct {
	RequestId            uint64                        `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success              bool                          `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Errors               map[string]*_struct.ListValue `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Data                 *Token                        `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *TokenCreateResponse) Reset()         { *m = TokenCreateResponse{} }
func (m *TokenCreateResponse) String() string { return proto.CompactTextString(m) }
func (*TokenCreateResponse) ProtoMessage()    {}
func (*TokenCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56b81cc36ca68ccc, []int{1}
}

func (m *TokenCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenCreateResponse.Unmarshal(m, b)
}
func (m *TokenCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenCreateResponse.Marshal(b, m, deterministic)
}
func (m *TokenCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenCreateResponse.Merge(m, src)
}
func (m *TokenCreateResponse) XXX_Size() int {
	return xxx_messageInfo_TokenCreateResponse.Size(m)
}
func (m *TokenCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TokenCreateResponse proto.InternalMessageInfo

func (m *TokenCreateResponse) GetRequestId() uint64 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *TokenCreateResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *TokenCreateResponse) GetErrors() map[string]*_struct.ListValue {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *TokenCreateResponse) GetData() *Token {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*TokenCreateRequest)(nil), "bigfile.token_create.TokenCreateRequest")
	proto.RegisterType((*TokenCreateResponse)(nil), "bigfile.token_create.TokenCreateResponse")
	proto.RegisterMapType((map[string]*_struct.ListValue)(nil), "bigfile.token_create.TokenCreateResponse.ErrorsEntry")
}

func init() { proto.RegisterFile("token_create.proto", fileDescriptor_56b81cc36ca68ccc) }

var fileDescriptor_56b81cc36ca68ccc = []byte{
	// 531 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x25, 0x49, 0xd7, 0x8f, 0x5b, 0x09, 0x26, 0x53, 0x89, 0xa8, 0x1a, 0xac, 0xea, 0x53, 0x91,
	0x50, 0x36, 0x75, 0x20, 0x3e, 0xde, 0x28, 0xea, 0xc3, 0x04, 0x88, 0x2a, 0xb4, 0x20, 0xed, 0x25,
	0x72, 0x93, 0xbb, 0x62, 0x2d, 0xb5, 0x8d, 0xed, 0x6c, 0xf4, 0xcf, 0xf0, 0xc0, 0x13, 0xe2, 0x17,
	0xf2, 0x88, 0xe2, 0xb8, 0x53, 0x37, 0x3a, 0xa9, 0x6f, 0xb9, 0xf7, 0x9e, 0x73, 0x7c, 0x7d, 0x8e,
	0x03, 0xc4, 0x88, 0x0b, 0xe4, 0x49, 0xaa, 0x90, 0x1a, 0x8c, 0xa4, 0x12, 0x46, 0x90, 0xce, 0x9c,
	0x2d, 0xce, 0x59, 0x8e, 0xd1, 0xe6, 0xac, 0xdb, 0xb6, 0x55, 0x05, 0xe9, 0x3e, 0x59, 0x08, 0xb1,
	0xc8, 0xf1, 0xc8, 0x56, 0xf3, 0xe2, 0xfc, 0xe8, 0x4a, 0x51, 0x29, 0x51, 0x69, 0x37, 0x3f, 0xbc,
	0x3d, 0x37, 0x6c, 0x89, 0xda, 0xd0, 0xa5, 0x74, 0x80, 0x83, 0xdb, 0x00, 0x6d, 0x54, 0x91, 0x9a,
	0x6a, 0xda, 0xff, 0x1d, 0x00, 0x99, 0x96, 0xc7, 0xbd, 0xb3, 0x67, 0xc7, 0xf8, 0xbd, 0x40, 0x6d,
	0xc8, 0x23, 0x68, 0x50, 0x29, 0x93, 0x82, 0x65, 0xa1, 0xd7, 0xf3, 0x06, 0xad, 0xb8, 0x4e, 0xa5,
	0x9c, 0xb1, 0x8c, 0x74, 0x60, 0x8f, 0x0b, 0x9e, 0x62, 0xe8, 0xdb, 0x76, 0x55, 0x10, 0x02, 0x35,
	0xcd, 0x16, 0x3c, 0x0c, 0x6c, 0xd3, 0x7e, 0x93, 0x63, 0xa8, 0x49, 0x6a, 0xbe, 0x85, 0xb5, 0x9e,
	0x37, 0x68, 0x0f, 0x0f, 0xa2, 0x6a, 0x8d, 0x68, 0xbd, 0x46, 0xf4, 0xd9, 0x28, 0xc6, 0x17, 0x5f,
	0x68, 0x5e, 0x60, 0x6c, 0x91, 0xe4, 0x19, 0xf8, 0x4c, 0x86, 0x7b, 0x3b, 0xe0, 0x7d, 0x26, 0xc9,
	0x73, 0xa8, 0x6b, 0x4c, 0x15, 0x9a, 0xb0, 0xbe, 0x03, 0xc3, 0x61, 0xc9, 0x18, 0x1e, 0xd0, 0x4b,
	0xca, 0x72, 0x3a, 0xcf, 0x31, 0xb1, 0x56, 0x85, 0x8d, 0x3b, 0xe8, 0xb3, 0x53, 0x6e, 0x4e, 0x86,
	0x15, 0xfd, 0xfe, 0x35, 0x69, 0x5a, 0x72, 0xc8, 0x4b, 0x68, 0x29, 0xa4, 0x59, 0x22, 0x78, 0xbe,
	0x0a, 0x9b, 0x56, 0xa0, 0xfb, 0x9f, 0xc0, 0x48, 0x88, 0xbc, 0xa2, 0x37, 0x4b, 0xf0, 0x27, 0x9e,
	0xaf, 0xc8, 0x6b, 0x00, 0xfc, 0x21, 0x99, 0xc2, 0x2c, 0xa1, 0x26, 0x6c, 0xdd, 0xc1, 0x9c, 0xae,
	0x33, 0x8c, 0x5b, 0x0e, 0xfd, 0xd6, 0xf4, 0x7f, 0xfa, 0xf0, 0xf0, 0x46, 0x54, 0x5a, 0x0a, 0xae,
	0x91, 0x3c, 0x06, 0x50, 0x55, 0x6c, 0x89, 0x8b, 0xab, 0x16, 0xb7, 0x5c, 0xe7, 0x34, 0x23, 0x21,
	0x34, 0x74, 0x91, 0xa6, 0xa8, 0xb5, 0xcd, 0xac, 0x19, 0xaf, 0x4b, 0xf2, 0x11, 0xea, 0xa8, 0x94,
	0x50, 0x3a, 0x0c, 0x7a, 0xc1, 0xa0, 0x3d, 0x7c, 0x11, 0x6d, 0x7b, 0x8e, 0xd1, 0x96, 0x33, 0xa3,
	0xb1, 0xe5, 0x8d, 0xb9, 0x51, 0xab, 0xd8, 0x89, 0x90, 0x01, 0xd4, 0x32, 0x6a, 0xa8, 0x0b, 0xbc,
	0x73, 0x53, 0xac, 0x52, 0x89, 0x2d, 0xa2, 0x3b, 0x83, 0xf6, 0x86, 0x00, 0xd9, 0x87, 0xe0, 0x02,
	0x57, 0xee, 0xa1, 0x95, 0x9f, 0xe4, 0x18, 0xf6, 0x2e, 0x4b, 0xe3, 0xec, 0xc6, 0xdb, 0x0c, 0xfa,
	0xc0, 0xb4, 0xa9, 0xac, 0xad, 0x80, 0x6f, 0xfc, 0x57, 0xde, 0x50, 0x43, 0x7b, 0x63, 0x57, 0x92,
	0x41, 0xf5, 0x23, 0xb9, 0x72, 0xb0, 0xc3, 0xed, 0xac, 0x67, 0xdd, 0xa7, 0x3b, 0xfb, 0xd0, 0xbf,
	0x37, 0x3a, 0x83, 0x4e, 0x2a, 0x96, 0xd7, 0x8c, 0xf5, 0x86, 0xa3, 0xfd, 0x0d, 0xf8, 0xa4, 0x6c,
	0x4e, 0xbc, 0xb3, 0x40, 0xc9, 0xf4, 0xaf, 0xe7, 0xfd, 0xf2, 0x83, 0xd1, 0x24, 0xfe, 0xe3, 0x1f,
	0x8e, 0x1c, 0x69, 0xb2, 0xbe, 0xd6, 0x57, 0xcc, 0xf3, 0xf7, 0x5c, 0x5c, 0xf1, 0xe9, 0x4a, 0xa2,
	0x9e, 0xd7, 0xad, 0xda, 0xc9, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc3, 0x4c, 0xee, 0xde, 0x3b,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TokenCreateClient is the client API for TokenCreate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TokenCreateClient interface {
	TokenCreate(ctx context.Context, in *TokenCreateRequest, opts ...grpc.CallOption) (*TokenCreateResponse, error)
}

type tokenCreateClient struct {
	cc *grpc.ClientConn
}

func NewTokenCreateClient(cc *grpc.ClientConn) TokenCreateClient {
	return &tokenCreateClient{cc}
}

func (c *tokenCreateClient) TokenCreate(ctx context.Context, in *TokenCreateRequest, opts ...grpc.CallOption) (*TokenCreateResponse, error) {
	out := new(TokenCreateResponse)
	err := c.cc.Invoke(ctx, "/bigfile.token_create.TokenCreate/tokenCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenCreateServer is the server API for TokenCreate service.
type TokenCreateServer interface {
	TokenCreate(context.Context, *TokenCreateRequest) (*TokenCreateResponse, error)
}

// UnimplementedTokenCreateServer can be embedded to have forward compatible implementations.
type UnimplementedTokenCreateServer struct {
}

func (*UnimplementedTokenCreateServer) TokenCreate(ctx context.Context, req *TokenCreateRequest) (*TokenCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TokenCreate not implemented")
}

func RegisterTokenCreateServer(s *grpc.Server, srv TokenCreateServer) {
	s.RegisterService(&_TokenCreate_serviceDesc, srv)
}

func _TokenCreate_TokenCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenCreateServer).TokenCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bigfile.token_create.TokenCreate/TokenCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenCreateServer).TokenCreate(ctx, req.(*TokenCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TokenCreate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bigfile.token_create.TokenCreate",
	HandlerType: (*TokenCreateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "tokenCreate",
			Handler:    _TokenCreate_TokenCreate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "token_create.proto",
}
